apiVersion: v1
kind: Service
metadata:
  name: redis-slave00
  namespace: redis
  labels:
    app: redis
    role: slave
    tier: backend
    slave: "00"
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis
    role: slave
    tier: backend
    slave: "00"
  type: LoadBalancer