apiVersion: v1
kind: Service
metadata:
  name: redis-leader01
  namespace: redis
  labels:
    app: redis
    role: leader
    tier: backend
    leader: "01"
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis
    role: leader
    tier: backend
    leader: "01"
  type: LoadBalancer