apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: docker.io/redis:6.0.5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["redis-server"]
        args: ["--slaveof", "redis-master.redis.svc.cluster.local", "6379", "--protected-mode", "no"]
        #env:
        #- name: REDIS_REPLICATION_MODE
        #  value: slave
        #- name: REDIS_MASTER_HOST
        #  value: redis-master.redis.svc.cluster.local
        #- name: REDIS_MASTER_PORT_NUMBER
        #  value: "6379"
        ports:
        - containerPort: 6379
