apiVersion: v1
kind: Service
metadata:
  name: redis-insight-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8001
  selector:
    app: redis-insight
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  labels:
    app: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name:  redisinsight
        image: redislabs/redisinsight:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: db
          mountPath: /db
        ports:
        - containerPort: 8001
          protocol: TCP
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: redis-insight-data